from __future__ import annotations

import warnings

import narwhals as nw
import numpy as np

from tab_err._utils import check_error_rate, get_column, get_column_str

from ._error_mechanism import ErrorMechanism


class EAR(ErrorMechanism):
    """`ErrorMechanism` subclass implementing the `Erroneous At Random` error mechanism.

    Description:
        Errors are assumed to depend on another column's values
    """

    def _sample(self: EAR, data: nw.DataFrame, column: str | int, error_rate: float, error_mask: nw.DataFrame) -> nw.DataFrame:
        """Creates an error mask according to the `Erroneous At Random` error mechanism.

        Description:
            A random index is chosen using a random number generator to create a range of indices.
            The error free data is then sorted by the value in the conditioning column and the error mask is generated by selecting a contiguous block of
                sorted entries, thereby having similar values, and marking these entries `True` in the mask.
            This ensures that occurrence of errors is related to the value of the another `column`.

        Args:
            data (nw.DataFrame): `DataFrame` containing the column to add errors to
            column (str | int): The column of `data` to create an error mask for
            error_rate (float): Proportion of rows to be affected by errors; in range [0,1]
            error_mask (nw.DataFrame): A `DataFrame` with the same index & columns as `data` that will be modified and returned

        Raises:
            ValueError: If there are fewer than two columns in `data`, a `ValueError` will be returned
            ValueError: If there are insufficient entries to add errors to with respect to the error rate, a `ValueError` will be returned

        Returns:
            nw.DataFrame: A `DataFrame` with `True` values at entries where an error should be introduced, `False` otherwise
        """
        check_error_rate(error_rate)

        if len(data.columns) < 2:  # noqa: PLR2004
            msg = "The data into which error at random (EAR) are to be injected requires at least 2 columns."
            raise ValueError(msg)

        col = get_column_str(data, column)

        if self.condition_to_column is None:
            column_selection = [x for x in data.columns if x != col]
            condition_to_column = self._random_generator.choice(column_selection)
            warnings.warn(
                "The user did not specify 'condition_to_column', the column on which the EAR Mechanism conditions the error distribution. "
                + f"Randomly select column '{condition_to_column}'.",
                stacklevel=1,
            )
        else:
            condition_to_column = get_column_str(data, self.condition_to_column)

        se_data = get_column(data, column)
        se_mask = get_column(error_mask, column)
        se_condition = get_column(data, condition_to_column)

        n_errors = int(len(se_data) * error_rate)

        # Get arrays
        mask_arr = se_mask.to_numpy()
        condition_arr = se_condition.to_numpy()

        # Get indices where mask is False (error-free cells)
        error_free_indices = np.where(~mask_arr)[0]

        if len(error_free_indices) < n_errors:
            msg = f"The error rate of {error_rate} requires {n_errors} error-free cells. "
            msg += f"However, only {len(error_free_indices)} error-free cells are available."
            raise ValueError(msg)

        # Get values at error-free indices from the conditioning column and sort them
        error_free_condition_values = condition_arr[error_free_indices]
        sorted_order = np.argsort(error_free_condition_values)
        sorted_error_free_indices = error_free_indices[sorted_order]

        # Calculate upper bound for lower_error_index
        upper_bound = len(error_free_indices) - n_errors
        lower_error_index = self._random_generator.integers(0, upper_bound) if upper_bound > 0 else 0
        selected_indices = sorted_error_free_indices[lower_error_index : lower_error_index + n_errors]

        # Create new mask array with selected indices set to True
        new_mask_arr = mask_arr.copy()
        new_mask_arr[selected_indices] = True

        # Update the error_mask DataFrame
        return error_mask.with_columns(nw.new_series(col, new_mask_arr.tolist(), backend=nw.get_native_namespace(error_mask)))
