from __future__ import annotations

import warnings

import narwhals as nw
import numpy as np

from tab_err._utils import check_error_rate, get_column, get_column_str

from ._error_mechanism import ErrorMechanism


class ENAR(ErrorMechanism):
    """`ErrorMechanism` subclass implementing the `Erroneous Not At Random` error mechanism.

    Description:
        Errors are assumed to depend on either other variables, the incorrect data itself, or both.
    """

    def _sample(self: ENAR, data: nw.DataFrame, column: str | int, error_rate: float, error_mask: nw.DataFrame) -> nw.DataFrame:
        """Creates an error mask according to the `Erroneous Not At Random` error mechanism.

        Description:
            A random index is chosen using a random number generator to create a range of indices.
            The error free data is then sorted by value and the error mask is generated by selecting a contiguous block of sorted entries,
                thereby having similar values, and marking these entries true in the mask.
            This ensures that occurrence of errors is related to the value of the variable.


        Args:
            data (nw.DataFrame): DataFrame containing the column to add errors to
            column (str | int): The column of `data` to create an error mask for
            error_rate (float): Proportion of rows to be affected by errors; in range [0,1]
            error_mask (nw.DataFrame): A `DataFrame` with the same index & columns as `data` that will be modified and returned

        Raises:
            ValueError: If there are insufficient entries to add errors to with respect to the error rate, `a` ValueError will be returned

        Returns:
            nw.DataFrame: A DataFrame with `True` values at entries where an error should be introduced, `False` otherwise
        """
        check_error_rate(error_rate)
        col_name = get_column_str(data, column)
        se_data = get_column(data, column)
        se_mask = get_column(error_mask, column)

        if self.condition_to_column is not None:
            warnings.warn("'condition_to_column' is set but will be ignored by ENAR.", stacklevel=1)

        n_rows = len(se_data)
        n_errors = int(n_rows * error_rate)

        # Get arrays
        data_arr = se_data.to_numpy()
        mask_arr = se_mask.to_numpy()

        # Get indices where mask is False (error-free cells)
        error_free_indices = np.where(~mask_arr)[0]

        if len(error_free_indices) < n_errors:
            msg = f"The error rate of {error_rate} requires {n_errors} error-free cells. "
            msg += f"However, only {len(error_free_indices)} error-free cells are available."
            raise ValueError(msg)

        # Get values at error-free indices and sort them
        error_free_values = data_arr[error_free_indices]
        sorted_order = np.argsort(error_free_values)
        sorted_error_free_indices = error_free_indices[sorted_order]

        # Choose a contiguous block of indices from the sorted error-free data
        lower_error_index = self._random_generator.integers(0, len(error_free_indices) - n_errors) if len(error_free_indices) != n_errors else 0
        selected_indices = sorted_error_free_indices[lower_error_index : lower_error_index + n_errors]

        # Create new mask array with selected indices set to True
        new_mask_arr = mask_arr.copy()
        new_mask_arr[selected_indices] = True

        # Update the error_mask DataFrame
        return error_mask.with_columns(nw.new_series(col_name, new_mask_arr.tolist(), backend=nw.get_native_namespace(error_mask)))
