default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      # Run the linter and fix issues ...
      - id: ruff
        types_or: [python, jupyter]
        args: [--fix]

      # ... then format.
      - id: ruff-format
        types_or: [python, jupyter]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        types: [python]
