name: mypy

on:
  - pull_request

jobs:
  mypy:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      #----------------------------------------------
      #        -----  install uv  -----
      #----------------------------------------------
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "0.7.3"

      #----------------------------------------------
      #  -----  setup matchers & run mypy   -----
      #----------------------------------------------
      - name: Setup matchers
        run: |
          echo "::add-matcher::.github/workflows/matchers/mypy.json"
          echo "TERM: changing from $TERM -> xterm"
          export TERM=xterm
      - name: Run mypy
        run: |
          # NOTE: tomli is sometimes missing, using dedicated ci dependencies
          uv run --group ci mypy --show-column-numbers .
