name: Pytest

on:
  - pull_request

jobs:
  Test:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      #----------------------------------------------
      #       Check out repo and set up Python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      #----------------------------------------------
      #        Install uv
      #----------------------------------------------
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "0.7.3"

      #----------------------------------------------
      #            Run Pytest
      #----------------------------------------------
      - name: Run tests with pytest
        run: uv run pytest --maxfail=5 --disable-warnings --tb=short
